---

- name: Copying keys
  copy:
    content: "{{ item.key }}"
    dest: "{{ openssl_keys_path }}/{{ item.name }}.key"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0600') }}"
  with_items: openssl_keys

- name: Copying certs
  copy:
    content: "{{ item.cert }}"
    dest: "{{ openssl_certs_path }}/{{ item.name }}.crt"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: openssl_certs

- name: Creating self-signed server SSL cert
  command: >
    openssl req -new
      -x509
      -nodes
      -extensions v3_ca
      -days {{ item.days|default(3650) }}
      -subj "/C={{ item.country|default('') }}/ST={{ item.state|default('') }}/L={{ item.city|default('') }}/O={{ item.organization|default('') }}/OU={{ item.unit|default('') }}{% if item.domains is defined %}{% for domain in item.domains %}/CN={{ domain }}{% endfor %}{% else %}/CN={{ item.name }}{% endif %}/emailAddress={{ item.email|default('') }}"
      -keyout {{ openssl_keys_path }}/{{ item.name }}.key
      -out {{ openssl_certs_path }}/{{ item.name }}.crt
  args:
    creates: "{{ openssl_certs_path }}/{{ item.name }}.crt"
  with_items: openssl_self_signed
